### ISSUE TITLE
Unable to cause item selection

### ISSUE THREAD

**Issue by pm64** [Keflon/FunctionZero.Maui.Controls#6]
Hey @Keflon, I'm trying to implement checkbox-based selection with TreeViewZero, and I'm getting some unexpected results.

If I understand the docs, we should be able to control an item's selection state by manipulating the IsSelected property of an item's templated parent. So shouldn't the following work?

```
<cz:TreeViewZero.TreeItemTemplate>
    <cz:TreeItemDataTemplate ChildrenPropertyName="Children" IsExpandedPropertyName="IsExpanded">
        <DataTemplate>
            <HorizontalStackLayout>
                <CheckBox IsChecked="{Binding Source={RelativeSource TemplatedParent}, Path=IsSelected, Mode=TwoWay}" />
                <Label
                    Padding="8,0,0,0"
                    Text="{Binding Label}"
                    VerticalTextAlignment="Center" />
            </HorizontalStackLayout>
        </DataTemplate>
    </cz:TreeItemDataTemplate>
</cz:TreeViewZero.TreeItemTemplate>
```

In my case the checkbox has no effect on SelectedItems, though it seems to be wired correctly. Any guidance would be greatly appreciated.

**Comment by Keflon** [comment]
Hi @pm64 
You can only use `TemplateBinding` from within a `ControlTemplate`. See [here.](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/relative-bindings#bind-to-a-templated-parent)  

`ListViewZero`, and therefore `TreeViewZero`, support selection using `SelectedItem` and `SelectedItems`. Neither of these are available from within the `ItemTemplate`, so you have two options I can think of.:

## Solution 1:

1. DataBind `TreeViewZero.SelectedItems` to an `ObservableCollection` in your ViewModel, e.g. `SelectedNodeList`, and hook the `CollectionChanged` event.
1. Databind your `CheckBox` to some ViewModel property on your _node_ ViewModel, e.g. `IsNodeSelected`.
1. If `IsNodeSelected` changes, add or remove the node from `SelectedNodeList` manually.
1. If the `SelectedNodeList` has items added or removed, modify `IsNodeSelected` on those items manually.  

There's a lot that could go wrong there, so I recommend a different approach.

## Solution 2: (Preferred)

Write a `ControlTemplate` for your TreeNodes and put your `CheckBox` in there.  
It can then access `IsSelected` and (optionally) `IsPrimary` using a `TemplateBinding`.  
This is the `CheckBox` you'll want:
```xaml
<CheckBox IsChecked="{Binding Source={RelativeSource TemplatedParent}, Path=IsSelected, Mode=TwoWay}" />
```
### Caution:
Make sure you set `SelectionMode` to `Multiple` or `Single`, otherwise tapping the `CheckBox` will lock up the UI because the `ListViewZero` will fight with it. I'll probably fix that soon enough.  

Here's a complete `TreeViewZero` with a `ControlTemplate` with the `CheckBox` in place. It is simply the default `ControlTemplate` with the `CheckBox` added. You will obviously have to supply your own `TreeItemTemplate`  

```xaml
<cz:TreeViewZero Grid.Row="2" Grid.Column="1" ItemsSource="{Binding SampleData}" IndentMultiplier="20" 
    SelectionMode="Multiple" ItemHeight="60">

    <cz:TreeViewZero.TreeItemControlTemplate>
        <ControlTemplate>
            <HorizontalStackLayout >
                <cz:TreeNodeSpacer />
                <cz:Chevron
                    VerticalOptions="Fill"
                    HorizontalOptions="Fill"
                    IsExpanded="{TemplateBinding BindingContext.IsExpanded, Mode=TwoWay}" 
                    ShowChevron="{TemplateBinding BindingContext.ShowChevron, Mode=TwoWay}" 
                />

                <CheckBox IsChecked="{Binding Source={RelativeSource TemplatedParent}, Path=IsSelected, Mode=TwoWay}" />

                <cz:TreeContentPresenter 
                    VerticalOptions="Fill" 
                    HorizontalOptions="Fill"   
                    BindingContext="{TemplateBinding BindingContext.Data, Mode=OneWay}"
                />
            </HorizontalStackLayout>

        </ControlTemplate>
    </cz:TreeViewZero.TreeItemControlTemplate>

    <cz:TreeViewZero.TreeItemTemplate>
        <cz:TreeItemDataTemplate ChildrenPropertyName="Children" IsExpandedPropertyName="IsDataExpanded">
            <DataTemplate>
                <HorizontalStackLayout>
                    <Label Text="{Binding Name}"/>
                </HorizontalStackLayout>
            </DataTemplate>
        </cz:TreeItemDataTemplate>
    </cz:TreeViewZero.TreeItemTemplate>

</cz:TreeViewZero>
```

You'll probably want your `ControlTemplate` in a `ResourceDictionary` somewhere so you can re-use it.  
  
Hope this helps, let me know how you get on :)

**Comment by pm64** [comment]
Thank you @Keflon, greatly appreciate your help.
