### ISSUE TITLE
ScrollTo() Method

### ISSUE THREAD

**Issue by SE250880** [Keflon/FunctionZero.Maui.Controls#7]
**First question:**
I would like to replace the traditional listview with ListViewZero. As an ItemSource I have connected a StringList that is filled dynamically. With every new entry in the string list, I would like to make it visible in the list and scroll the list accordingly in the backend to the new entry. But I'm missing the ScrollTo() method that the standard ListView has. Is there a workaround?

**Second-Question**
I would also like to use the list view without a fixed height within a scroll view. This worked fine in Xamarin. After the Maui migration, the default list view adjusts the height of the control incorrectly. Can the ListViewZero handle a parent scrollview?

**Comment by Keflon** [comment]
Hi @SE250880 

**First answer:**
There isn't a `ScrollTo` but you have much finer control because you can `TwoWay` bind to `ScrollOffset` 
giving you pixel control of the scroll position.

If your ViewModel has this:
```csharp
private double _listViewScrollOffset;
public double ListViewScrollOffset
{
    get => _listViewScrollOffset;
    set => SetProperty(ref _listViewScrollOffset, value);
}
```
and your `xaml` looks like this:
```xaml
<cz:ListViewZero 
    ItemsSource="{Binding SampleListData}"
    ScrollOffset="{Binding ListViewScrollOffset, Mode=TwoWay}" 
    ItemHeight="40"
    ...
>
```

You can then do something like this when you add an item or items to your collection:
```csharp
// Get the item index from somewhere, e.g. 'SampleListData.Count-1' if it's the end item.
ScrollOffset = 40 * itemIndex;
```

The next update will have a way of determining more information about the state of the `ScrollViewZero`, including the number of visible items, the index of the first visible item, the number of 'remaining items' before you run out of items to display, etc.  
This will help you position things within the render area, e.g. to scroll so an item is centred or at the top or bottom of the view, as well as allowing lazy-loading for infinite scroll.  

  **Second answer:**
I'm not entirely sure I understand the question, so please correct me if I've misunderstood ...  
The `ListViewZero` derives from a `ContentView` and has the `HorizontalOptions` and `VerticalOptions` set to `FillAndExpand`. You can override the default values yourself to any of the `LayoutOptions` so hopefully you can get it to size itself as any other control would.  
E.g. 
```xaml
<cz:ListViewZero 
    VerticalOptions="Start"
    ...
>
```
If you're trying to get the `ListViewZero` to behave when inside a vertical `ScrollView`, that's not going to work because `ListViewZero` uses a `ScrollView` and the [MAUI documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/scrollview) says we cannot nest a `ScrollView` inside a `ScrollView`.  
Having said that, it ought to size itself like any other control, so you may be running into [this](https://github.com/dotnet/maui/issues/15163) MAUI bug.

**Comment by SE250880** [comment]
**First**
Ok, that's a workaround for the moment, but I'm eagerly awaiting the next update that will make setting the scroll position easier.  :-)

**Secondly**
That doesn't help in my case and the Maui bug seems to be the problem here. I want to position the listview in a scrollview with the height of *. This looks fine until the list content gets to the end of the list. Then the whole control is enlarged to the content of the list. I don't want that, but the size should remain and the list should scroll. This worked fine in Xamarin, but not anymore with MAUI.  :-(
